services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8501"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    restart: unless-stopped