name: Update Speaker Data

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps
          
      - name: Run scraper
        run: |
          # Print environment info for debugging
          echo "Running scraper with company data enrichment enabled"
          python -c "import os; print(f'OPENAI_API_KEY set: {bool(os.getenv(\"OPENAI_API_KEY\"))}')"
          python -c "import os; print(f'ENABLE_COMPANY_ENRICHMENT: {os.getenv(\"ENABLE_COMPANY_ENRICHMENT\")}')"
          
          # Run the scraper
          python scraper_runner.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ENABLE_COMPANY_ENRICHMENT: "true"
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "borja.regueral@somniumrema.eu"
          git config --global user.name "GitHub Actions (Borja_Regueral)"
          
          # Remove any existing data files before adding the new ones
          git rm -f --ignore-unmatch data/speakers.json data/speakers.csv
          
          # Add the new data files
          git add -f data/speakers.json data/speakers.csv
          
          # Commit if there are changes
          git diff --staged --quiet || git commit -m "Update speaker data"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
