name: Update Speaker Data

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps
          
      - name: Run scraper
        run: python scraper_runner.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "borja.regueral@somniumrema.eu"
          git config --global user.name "GitHub Actions (Borja_Regueral)"
          git pull origin main
          git add -f data/speakers.json data/speakers.csv
          git commit -m "Update speaker data" || exit 0
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
